In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
df = pd.read_csv('full_data.csv')
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
4976,Male,41.0,0,0,No,Private,Rural,70.15,29.8,formerly smoked,0
4977,Male,40.0,0,0,Yes,Private,Urban,191.15,31.1,smokes,0
4978,Female,45.0,1,0,Yes,Govt_job,Rural,95.02,31.8,smokes,0
4979,Male,40.0,0,0,Yes,Private,Rural,83.94,30.0,smokes,0
4980,Female,80.0,1,0,Yes,Private,Urban,83.75,29.1,never smoked,0

In [18]:
df['stroke'].value_counts()

stroke
0    4733
1     248
Name: count, dtype: int64

In [19]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [20]:
x

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked
...,...,...,...,...,...,...,...,...,...,...
4976,Male,41.0,0,0,No,Private,Rural,70.15,29.8,formerly smoked
4977,Male,40.0,0,0,Yes,Private,Urban,191.15,31.1,smokes
4978,Female,45.0,1,0,Yes,Govt_job,Rural,95.02,31.8,smokes
4979,Male,40.0,0,0,Yes,Private,Rural,83.94,30.0,smokes
4980,Female,80.0,1,0,Yes,Private,Urban,83.75,29.1,never smoked

In [21]:
y

0       1
1       1
2       1
3       1
4       1
       ..
4976    0
4977    0
4978    0
4979    0
4980    0
Name: stroke, Length: 4981, dtype: int64

In [22]:
# using map function we encoding the data 
x['gender'].map({'Male':1,"female":0})

0       1.0
1       1.0
2       NaN
3       NaN
4       1.0
       ...
4976    1.0
4977    1.0
4978    NaN
4979    1.0
4980    NaN
Name: gender, Length: 4981, dtype: float64

In [1]:
# using label encoding we can convert categorical data into numerical 
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()

In [2]:
x['genderr'] = l1.fit_transform(x['gender'])
x['ever_married'] = l1.fit_transform(x['ever_married'])
x['work_type'] = l1.fit_transform(x['work_type'])
x['Residence_type'] = l1.fit_transform(x['Residence_type'])
x['smoking_status'] = l1.fit_transform(x['smoking_status'])

NameError: name 'x' is not defined

In [3]:
from imblearn.under_sampling import NearMiss
ab = NearMiss()
x_res,y_res = ab.fit_resample(x,y)

ImportError: cannot import name '_safe_tags' from 'sklearn.utils._tags' (C:\Users\Kiran Maske\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_tags.py)

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # Converts 'Male'/'Female' into numbers

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=35)

NameError: name 'x' is not defined