In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [4]:
# using label encoding we can convert categorical data into numerical 
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()

In [30]:
df['Species'] = l1.fit_transform(df['Species'])

In [32]:
df['Species'].value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [14]:
df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [7]:
x= df.iloc[:,:-1]
y = df.iloc[:,-1]

In [8]:
x

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [9]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_train

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137  138            6.4           3.1            5.5           1.8
84    85            5.4           3.0            4.5           1.5
27    28            5.2           3.5            1.5           0.2
127  128            6.1           3.0            4.9           1.8
132  133            6.4           2.8            5.6           2.2
..   ...            ...           ...            ...           ...
9     10            4.9           3.1            1.5           0.1
103  104            6.3           2.9            5.6           1.8
67    68            5.8           2.7            4.1           1.0
117  118            7.7           3.8            6.7           2.2
47    48            4.6           3.2            1.4           0.2

[120 rows x 5 columns]

In [12]:
y_train

137    2
84     1
27     0
127    2
132    2
      ..
9      0
103    2
67     1
117    2
47     0
Name: Species, Length: 120, dtype: int64

In [15]:
x_test

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
114  115            5.8           2.8            5.1           2.4
62    63            6.0           2.2            4.0           1.0
33    34            5.5           4.2            1.4           0.2
107  108            7.3           2.9            6.3           1.8
7      8            5.0           3.4            1.5           0.2
100  101            6.3           3.3            6.0           2.5
40    41            5.0           3.5            1.3           0.3
86    87            6.7           3.1            4.7           1.5
76    77            6.8           2.8            4.8           1.4
71    72            6.1           2.8            4.0           1.3
134  135            6.1           2.6            5.6           1.4
51    52            6.4           3.2            4.5           1.5
73    74            6.1           2.8            4.7           1.2
54    55            6.5           2.8            4.6           1.5
63    64            6.1           2.9            4.7           1.4
37    38            4.9           3.1            1.5           0.1
78    79            6.0           2.9            4.5           1.5
90    91            5.5           2.6            4.4           1.2
45    46            4.8           3.0            1.4           0.3
16    17            5.4           3.9            1.3           0.4
121  122            5.6           2.8            4.9           2.0
66    67            5.6           3.0            4.5           1.5
24    25            4.8           3.4            1.9           0.2
8      9            4.4           2.9            1.4           0.2
126  127            6.2           2.8            4.8           1.8
22    23            4.6           3.6            1.0           0.2
44    45            5.1           3.8            1.9           0.4
97    98            6.2           2.9            4.3           1.3
93    94            5.0           2.3            3.3           1.0
26    27            5.0           3.4            1.6           0.4

In [16]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
Name: Species, dtype: int64

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)
knn.fit(x_train, y_train)

KNeighborsClassifier(p=1)

In [20]:
y_pred = knn.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [ ]:
y_pred = knn.predict(x_test)
y_pred

In [21]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
Name: Species, dtype: int64

In [27]:
print('KNN accuracy =',knn.score(x_train,y_train)*100)

KNN accuracy = 100.0