In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('insurance1.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()

In [8]:
df['region'] = l1.fit_transform(df['region'])

In [9]:
df['region'].value_counts()

region
2    364
3    325
1    325
0    324
Name: count, dtype: int64

In [10]:
df

      age     sex     bmi  children smoker  region      charges
0      19  female  27.900         0    yes       3  16884.92400
1      18    male  33.770         1     no       2   1725.55230
2      28    male  33.000         3     no       2   4449.46200
3      33    male  22.705         0     no       1  21984.47061
4      32    male  28.880         0     no       1   3866.85520
...   ...     ...     ...       ...    ...     ...          ...
1333   50    male  30.970         3     no       1  10600.54830
1334   18  female  31.920         0     no       0   2205.98080
1335   18  female  36.850         0     no       2   1629.83350
1336   21  female  25.800         0     no       3   2007.94500
1337   61  female  29.070         0    yes       1  29141.36030

[1338 rows x 7 columns]

In [11]:
x= df.iloc[:,:-1]
y = df.iloc[:,-1]

In [12]:
x

      age     sex     bmi  children smoker  region
0      19  female  27.900         0    yes       3
1      18    male  33.770         1     no       2
2      28    male  33.000         3     no       2
3      33    male  22.705         0     no       1
4      32    male  28.880         0     no       1
...   ...     ...     ...       ...    ...     ...
1333   50    male  30.970         3     no       1
1334   18  female  31.920         0     no       0
1335   18  female  36.850         0     no       2
1336   21  female  25.800         0     no       3
1337   61  female  29.070         0    yes       1

[1338 rows x 6 columns]

In [13]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
x_train

      age     sex     bmi  children smoker  region
621    37    male  34.100         4    yes       3
194    18    male  34.430         0     no       2
240    23  female  36.670         2    yes       0
1168   32    male  35.200         2     no       3
1192   58  female  32.395         1     no       0
...   ...     ...     ...       ...    ...     ...
763    27    male  26.030         0     no       0
835    42    male  35.970         2     no       2
1216   40    male  25.080         0     no       2
559    19    male  35.530         0     no       1
684    33  female  18.500         1     no       3

[1070 rows x 6 columns]

In [16]:
x_test

      age     sex     bmi  children smoker  region
578    52    male  30.200         1     no       3
610    47  female  29.370         1     no       2
569    48    male  40.565         2    yes       1
1034   61    male  38.380         0     no       1
198    51  female  18.050         0     no       1
...   ...     ...     ...       ...    ...     ...
1084   62  female  30.495         2     no       1
726    41    male  28.405         1     no       1
1132   57    male  40.280         0     no       0
725    30  female  39.050         3    yes       2
963    46    male  24.795         3     no       0

[268 rows x 6 columns]

In [17]:
y_train

621     40182.24600
194      1137.46970
240     38511.62830
1168     4670.64000
1192    13019.16105
           ...
763      3070.80870
835      7160.33030
1216     5415.66120
559      1646.42970
684      4766.02200
Name: charges, Length: 1070, dtype: float64

In [18]:
y_test

578      9724.53000
610      8547.69130
569     45702.02235
1034    12950.07120
198      9644.25250
           ...
1084    15019.76005
726      6664.68595
1132    20709.02034
725     40932.42950
963      9500.57305
Name: charges, Length: 268, dtype: float64

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)
knn.fit(x_train, y_train)

ValueError: could not convert string to float: 'male'