In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('insurance1.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df['children'].value_counts()

children
0    574
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

In [6]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [7]:
x

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [8]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [14]:
# using map function we encoding the data 
x['sex'].map({'Male':19,"female":18})

0       18.0
1        NaN
2        NaN
3        NaN
4        NaN
        ...
1333     NaN
1334    18.0
1335    18.0
1336    18.0
1337    18.0
Name: sex, Length: 1338, dtype: float64

In [15]:
# using label encoding we can convert categorical data into numerical 
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()

In [17]:
x['age'] = l1.fit_transform(x['age'])
x['sex'] = l1.fit_transform(x['sex'])
x['bmi'] = l1.fit_transform(x['bmi'])
x['children'] = l1.fit_transform(x['children'])
x['smoker'] = l1.fit_transform(x['smoker'])