In [4]:
import pandas as pd
import numpy as np

In [5]:
# DataFrame
data1 = {
    "ID":[1,2,3,4,5,6],
    "Name":["A","B","C","D","E","F"],
    "Salary":[1000,3000,2000,4452,5123,54220],
    "City":["Pune","Satara","Sangli","Kolhapur","Mumbai","Karad"]
}

In [6]:
dataset = pd.DataFrame(data1)
dataset

   ID Name  Salary      City
0   1    A    1000      Pune
1   2    B    3000    Satara
2   3    C    2000    Sangli
3   4    D    4452  Kolhapur
4   5    E    5123    Mumbai
5   6    F   54220     Karad

In [7]:
dataset["Salary"]

0     1000
1     3000
2     2000
3     4452
4     5123
5    54220
Name: Salary, dtype: int64

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      object
 2   Salary  6 non-null      int64
 3   City    6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [9]:
dataset.head()

   ID Name  Salary      City
0   1    A    1000      Pune
1   2    B    3000    Satara
2   3    C    2000    Sangli
3   4    D    4452  Kolhapur
4   5    E    5123    Mumbai

In [10]:
dataset.head(2)

   ID Name  Salary    City
0   1    A    1000    Pune
1   2    B    3000  Satara

In [11]:
dataset.tail()

   ID Name  Salary      City
1   2    B    3000    Satara
2   3    C    2000    Sangli
3   4    D    4452  Kolhapur
4   5    E    5123    Mumbai
5   6    F   54220     Karad

In [12]:
dataset.describe()

             ID        Salary
count  6.000000      6.000000
mean   3.500000  11632.500000
std    1.870829  20918.812086
min    1.000000   1000.000000
25%    2.250000   2250.000000
50%    3.500000   3726.000000
75%    4.750000   4955.250000
max    6.000000  54220.000000

In [13]:
# aggrigation function()
dataset["Salary"].mean()

np.float64(11632.5)

In [14]:
dataset["Salary"].min()

np.int64(1000)

In [15]:
dataset["Salary"].max()

np.int64(54220)

In [17]:
dataset["Salary"].count()

np.int64(6)

In [18]:
dataset["Salary"].sum()

np.int64(69795)

In [19]:
# 2.using CSV
df = pd.read_csv("D:\\Internship_June2025\\AllData\\weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [20]:
# 3.excel
# pip install openpyxl
df = pd.read_excel("D:\\Internship_June2025\\AllData\\weather_data.xlsx","Sheet1")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [18]:
# 4. using tuple list 
weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow'),
]
dataset = pd.DataFrame(data = weather_data,columns = ['day','temperature','windspeed','event'])
dataset

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [23]:
# 5.List of Dictonaries
weather_data =[
    {'day':'1/1/2017','temperature': 32, 'windspeed': 6, 'event':'Rain'},
    {'day':'1/2/2017','temperature': 35, 'windspeed': 7, 'event':'Sunny'},
    {'day':'1/3/2017','temperature': 28, 'windspeed': 2, 'event':'Snow'},
    ]
dataset = pd.DataFrame(data = weather_data,columns = ['day','temperature','windspeed','event'])
dataset

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow