In [65]:
#Handling nullvalues
import pandas as pd
import numpy as np

In [66]:
dataset = pd.read_csv(r"D:\Data Science All\Pandas\AllData\train.csv")
dataset

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,Owner,0,0,3,BHK,2500.000000,1,1,"Shamshabad Road,Agra",27.140626,78.043277,45.0
29447,Owner,0,0,2,BHK,769.230769,1,1,"E3-108, Lake View Recidency,,Vapi",39.945409,-86.150721,16.0
29448,Dealer,0,0,2,BHK,1022.641509,1,1,"Ajmer Road,Jaipur",26.928785,75.828002,27.1
29449,Owner,0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,"Jagatpura,Jaipur",26.832353,75.841749,27.8

In [67]:
dataset.shape

(29451, 12)

In [68]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  object
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  object
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  object
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 2.7+ MB

In [69]:
dataset.isnull()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,False,False,False,False,False,False,False,False,False,False,False,False
29447,False,False,False,False,False,False,False,False,False,False,False,False
29448,False,False,False,False,False,False,False,False,False,False,False,False
29449,False,False,False,False,False,False,False,False,False,False,False,False
29450,False,False,False,False,False,False,False,False,False,False,False,False

In [70]:
dataset.notnull()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,True,True,True,True,True,True,True,True,True,True,True,True
29447,True,True,True,True,True,True,True,True,True,True,True,True
29448,True,True,True,True,True,True,True,True,True,True,True,True
29449,True,True,True,True,True,True,True,True,True,True,True,True
29450,True,True,True,True,True,True,True,True,True,True,True,True

In [71]:
dataset.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
ADDRESS                  0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [72]:
dataset = pd.read_csv(r"D:\Data Science All\Pandas\AllData\titanic.csv")
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [73]:
dataset['age'] = dataset['age'].fillna(25)
dataset.head(25)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,25.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,25.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,25.0,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [74]:
dataset.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [83]:
dataset = pd.read_csv(r"D:\Data Science All\Pandas\AllData\titanic.csv")
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [84]:
m = dataset['age'].mean()
m

29.69911764705882

In [85]:
ab = round(m,2)
ab

29.7

In [86]:
dataset['age'] = dataset['age'].fillna(ab)
dataset.head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,29.7,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,29.7,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,29.7,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True

In [87]:
dataset['sex']=dataset['sex'].replace("male","purush")
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,purush,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,purush,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,purush,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.7,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,purush,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,purush,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [89]:
for x in dataset['age']:
    print(x)

In [90]:
#loc and iloc --> loc: condition basis, iloc: rows and col basis

In [93]:
dataset = pd.read_csv(r"D:\Data Science All\Pandas\AllData\weatherHistory.csv")
dataset.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [94]:
dataset.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [95]:
dataset = dataset.dropna()
dataset

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [96]:
dataset.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [97]:
data = []
for x in dataset['Temperature (C)']:
    ab = x+2
    ab1 = round(ab,2)
    data.append(ab1)

In [99]:
data

In [100]:
dataset['New_temp'] = data
dataset

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,New_temp
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,11.47
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,11.36
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,11.38
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,10.29
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,10.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,28.02
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,26.58
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,24.04
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,23.52
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,22.44

In [101]:
dataset.insert(2,"Temp_update",data)
dataset

,Formatted Date,Summary,Temp_update,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,New_temp
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,11.47,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,11.47
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,11.36,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,11.36
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,11.38,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,11.38
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,10.29,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,10.29
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,10.76,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,10.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,28.02,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,28.02
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,26.58,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,26.58
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,24.04,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,24.04
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,23.52,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,23.52
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,22.44,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,22.44

In [102]:
del dataset['Temperature (C)']
dataset

,Formatted Date,Summary,Temp_update,Precip Type,Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,New_temp
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,11.47,rain,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,11.47
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,11.36,rain,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,11.36
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,11.38,rain,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,11.38
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,10.29,rain,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,10.29
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,10.76,rain,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,10.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,28.02,rain,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,28.02
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,26.58,rain,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,26.58
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,24.04,rain,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,24.04
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,23.52,rain,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,23.52
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,22.44,rain,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,22.44

In [105]:
dataset = pd.read_csv(r"D:\Data Science All\Pandas\AllData\tips.csv")
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [106]:
x = dataset.iloc[5:150,3:5]
x

    smoker   day
5       No   Sun
6       No   Sun
7       No   Sun
8       No   Sun
9       No   Sun
..     ...   ...
145     No  Thur
146     No  Thur
147     No  Thur
148     No  Thur
149     No  Thur

[145 rows x 2 columns]

In [107]:
x = dataset.iloc[5:150,3:-1]
x

    smoker   day    time
5       No   Sun  Dinner
6       No   Sun  Dinner
7       No   Sun  Dinner
8       No   Sun  Dinner
9       No   Sun  Dinner
..     ...   ...     ...
145     No  Thur   Lunch
146     No  Thur   Lunch
147     No  Thur   Lunch
148     No  Thur   Lunch
149     No  Thur   Lunch

[145 rows x 3 columns]

In [108]:
x = dataset.iloc[2:5,[1,3,5]]
x

    tip smoker    time
2  3.50     No  Dinner
3  3.31     No  Dinner
4  3.61     No  Dinner

In [109]:
#loc

In [110]:
data = dataset.loc[dataset['sex']=='Female']
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [111]:
data = dataset.loc[(dataset["sex"]=="Female")&(dataset["smoker"]=="Yes")&(dataset["tip"]>=2)&(dataset["tip"]<=4)]
data

     total_bill   tip     sex smoker   day    time  size
72        26.86  3.14  Female    Yes   Sat  Dinner     2
100       11.35  2.50  Female    Yes   Fri  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
109       14.31  4.00  Female    Yes   Sat  Dinner     2
164       17.51  3.00  Female    Yes   Sun  Dinner     2
169       10.63  2.00  Female    Yes   Sat  Dinner     2
178        9.60  4.00  Female    Yes   Sun  Dinner     2
186       20.90  3.50  Female    Yes   Sun  Dinner     3
188       18.15  3.50  Female    Yes   Sun  Dinner     3
198       13.00  2.00  Female    Yes  Thur   Lunch     2
201       12.74  2.01  Female    Yes  Thur   Lunch     2
202       13.00  2.00  Female    Yes  Thur   Lunch     2
203       16.40  2.50  Female    Yes  Thur   Lunch     2
205       16.47  3.23  Female    Yes  Thur   Lunch     3
209       12.76  2.23  Female    Yes   Sat  Dinner     2
213       13.27  2.50  Female    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
221       13.42  3.48  Female    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [114]:
#group by
df = pd.read_csv(r"D:\Data Science All\Pandas\AllData\weather_by_cities.csv")
df

           day      city  temperature  windspeed   event  Unnamed: 5
0   01-01-2017  new york           32          6    Rain         NaN
1   01-02-2017  new york           36          7   Sunny         NaN
2   01-03-2017  new york           28         12    Snow         NaN
3   01-04-2017  new york           33          7   Sunny         NaN
4   01-01-2017    mumbai           90          5   Sunny         NaN
5   01-02-2017    mumbai           85         12     Fog         NaN
6   01-03-2017    mumbai           87         15     Fog         NaN
7   01-04-2017    mumbai           92          5    Rain         NaN
8   01-01-2017     paris           45         20   Sunny         NaN
9   01-02-2017     paris           50         13  Cloudy         NaN
10  01-03-2017     paris           54          8  Cloudy         NaN
11  01-04-2017     paris           42         10  Cloudy         NaN

In [ ]:
# 1. what was the maximum temperature in each of these citis?
# 2.  what was the avg windspeed in each of these citis?

In [115]:
g = df.groupby('city')
g

In [116]:
for city,data in g:
    print("city : ",city)
    print("\n")
    print("data : ",data)

city :  mumbai


data :            day    city  temperature  windspeed  event  Unnamed: 5
4  01-01-2017  mumbai           90          5  Sunny         NaN
5  01-02-2017  mumbai           85         12    Fog         NaN
6  01-03-2017  mumbai           87         15    Fog         NaN
7  01-04-2017  mumbai           92          5   Rain         NaN
city :  new york


data :            day      city  temperature  windspeed  event  Unnamed: 5
0  01-01-2017  new york           32          6   Rain         NaN
1  01-02-2017  new york           36          7  Sunny         NaN
2  01-03-2017  new york           28         12   Snow         NaN
3  01-04-2017  new york           33          7  Sunny         NaN
city :  paris


data :             day   city  temperature  windspeed   event  Unnamed: 5
8   01-01-2017  paris           45         20   Sunny         NaN
9   01-02-2017  paris           50         13  Cloudy         NaN
10  01-03-2017  paris           54          8  Cloudy         NaN
11  01-04-2017  paris           42         10  Cloudy         NaN

In [117]:
g.get_group('mumbai')

          day    city  temperature  windspeed  event  Unnamed: 5
4  01-01-2017  mumbai           90          5  Sunny         NaN
5  01-02-2017  mumbai           85         12    Fog         NaN
6  01-03-2017  mumbai           87         15    Fog         NaN
7  01-04-2017  mumbai           92          5   Rain         NaN

In [118]:
g.min()

                 day  temperature  windspeed   event  Unnamed: 5
city
mumbai    01-01-2017           85          5     Fog         NaN
new york  01-01-2017           28          6    Rain         NaN
paris     01-01-2017           42          8  Cloudy         NaN

In [119]:
g.mean()

          temperature  windspeed  Unnamed: 5
city
mumbai          88.50       9.25         NaN
new york        32.25       8.00         NaN
paris           47.75      12.75         NaN

In [121]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed         ...              Unnamed: 5                       \
             count   mean  ...    75%   max      count mean std min 25% 50%
city                       ...
mumbai         4.0   9.25  ...  12.75  15.0        0.0  NaN NaN NaN NaN NaN
new york       4.0   8.00  ...   8.25  12.0        0.0  NaN NaN NaN NaN NaN
paris          4.0  12.75  ...  14.75  20.0        0.0  NaN NaN NaN NaN NaN


         75% max
city
mumbai   NaN NaN
new york NaN NaN
paris    NaN NaN

[3 rows x 24 columns]

In [122]:
#concatination:

In [124]:
india_weather = pd.DataFrame({
    "city":["mumbai","delhi","benglore"],
    "temperature":[32,45,30],
    "humidity":[80,60,78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  benglore           30        78

In [125]:
usa_weather = pd.DataFrame({
    "city":["newyork","chicago","orlando"],
    "temperature":[32,45,30],
    "humidity":[80,60,78]
})
usa_weather

      city  temperature  humidity
0  newyork           32        80
1  chicago           45        60
2  orlando           30        78

In [126]:
df = pd.concat([india_weather,usa_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  benglore           30        78
0   newyork           32        80
1   chicago           45        60
2   orlando           30        78

In [127]:
df = pd.concat([india_weather,usa_weather],ignore_index=True)
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  benglore           30        78
3   newyork           32        80
4   chicago           45        60
5   orlando           30        78

In [128]:
df = pd.concat([india_weather,usa_weather],keys=["India","USA"])
df

             city  temperature  humidity
India 0    mumbai           32        80
      1     delhi           45        60
      2  benglore           30        78
USA   0   newyork           32        80
      1   chicago           45        60
      2   orlando           30        78

In [130]:
df.loc["India"]

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  benglore           30        78

In [132]:
india_weather = pd.DataFrame({
    "city":["mumbai","delhi","benglore"],
    "temperature":[32,45,30],
},index=[0,1,2])
india_weather

       city  temperature
0    mumbai           32
1     delhi           45
2  benglore           30

In [133]:
india_weather = pd.DataFrame({
    "city":["mumbai","delhi"],
    "humidity":[80,60]
},index=[1,2])
india_weather

     city  humidity
1  mumbai        80
2   delhi        60

In [134]:
#Merge

In [135]:
df1 = pd.DataFrame({
    "city":["newyork","chicago","orlando"],
    "temperature":[21,14,35]
})
df1

      city  temperature
0  newyork           21
1  chicago           14
2  orlando           35

In [136]:
df2 = pd.DataFrame({
    "city":["chicago","newyork","orlando"],
    "humidity":[80,60,78]
})
df2

      city  humidity
0  chicago        80
1  newyork        60
2  orlando        78

In [139]:
df3 = pd.merge(df1,df2,on="city")
df3

      city  temperature  humidity
0  newyork           21        60
1  chicago           14        80
2  orlando           35        78

In [140]:
df1 = pd.DataFrame({
    "city":["newyork","chicago","orlando","baltimore"],
    "temperature":[21,14,35,38]
})
df1

        city  temperature
0    newyork           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [141]:
df2 = pd.DataFrame({
    "city":["chicago","newyork","san diego"],
    "humidity":[80,60,78]
})
df2

        city  humidity
0    chicago        80
1    newyork        60
2  san diego        78

In [142]:
df3 = pd.merge(df1,df2,on="city",how="inner")
df3

      city  temperature  humidity
0  newyork           21        60
1  chicago           14        80

In [143]:
df3 = pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0    newyork         21.0      60.0
1    chicago         14.0      80.0
2    orlando         35.0       NaN
3  baltimore         38.0       NaN
4  san diego          NaN      78.0

In [144]:
df3 = pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0    newyork           21      60.0
1    chicago           14      80.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [145]:
df3 = pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0    chicago         14.0        80
1    newyork         21.0        60
2  san diego          NaN        78